// ---------------- Custom Equipment Services ----------------
npc: npc/custom/equipment_services/full_refine.txt
npc: npc/custom/equipment_services/grade_enhancer.txt

// ----------------- Custom Zeny Enchanters ------------------
npc: npc/custom/enchant/enchan_arm_zeny.txt
npc: npc/custom/enchant/enchan_edda_half_moon_zeny.txt
npc: npc/custom/enchant/enchan_illusion_17_1_zeny.txt
npc: npc/custom/enchant/enchan_illusion_dungeons_zeny.txt
npc: npc/custom/enchant/enchan_ko_zeny.txt
npc: npc/custom/enchant/enchan_mal_zeny.txt
npc: npc/custom/enchant/enchan_mora_zeny.txt
npc: npc/custom/enchant/enchan_rockridge_zeny.txt
npc: npc/custom/enchant/enchan_sage_legacy_17_2_zeny.txt
npc: npc/custom/enchant/enchan_upg_zeny.txt
npc: npc/custom/enchant/enchan_verus_zeny.txt
npc: npc/custom/enchant/bio4_enchant_zeny.txt
npc: npc/custom/enchant/horror_toy_enchant_zeny.txt
npc: npc/custom/enchant/infinite_space_enchant_zeny.txt
npc: npc/custom/enchant/malangdo_costume_enchant_zeny.txt
npc: npc/custom/enchant/hero_ring_enchant_zeny.txt
npc: npc/custom/enchant/nightmare_biolab_enchant_zeny.txt
npc: npc/custom/enchant/old_glast_heim_enchant_zeny.txt
